# Generated by Django 3.1 on 2020-08-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcdapp', '0002_predictionrequestmodel_request_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrequestmodel',
            name='sound',
            field=models.FileField(default=0, upload_to='bcd_server/bcdapp/reqsounds/'),
        ),
    ]
